export 'movies/movies_provider.dart';
export 'movies/movies_usecase_provider.dart';
export 'movies/movie_detail_provider.dart';
export 'search/search_movies_provider.dart';
export 'actors/actors_bymovie_provider.dart';
export 'actors/actors_usecase_provider.dart';
export 'galery/galery_bymovie_provider.dart';
export 'galery/galery_usecase_provider.dart';
export 'localdb/localdb_usecase_provider.dart';